export const SQLITE_UNIQUE_CONSTRAINT_ERROR_CODE = 'SQLITE_CONSTRAINT_UNIQUE';
export const SQLITE_PRIMARY_CONSTRAINT_ERROR_CODE =
  'SQLITE_CONSTRAINT_PRIMARYKEY';

export const REQUEST_USER_KEY = 'user';
